### ISSUE TITLE
dossiers différents pour images et svg ?

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/alstart#1]
Quel intérêt de séparer les SVG des autres formats d'images ?

D'après le gulpfile, ça a l'air de bien compliquer les choses, alors que tout pourrait entre dans /img et stoo : 

```
// Tâche "img" = Images optimisées
gulp.task('img', function () {
  return gulp.src(source + '/assets/img/*.{png,jpg,jpeg,gif,svg}')
    .pipe(imagemin())
    .pipe(gulp.dest(prod + '/assets/img'));
});
``` 

Bisous

**Comment by id2** [comment]
Peut être la réduction d'image pour le svg n'est pas fortement probant 
comme c'est du vectoriel.
Ou bien qu'il y a peut être des bugs connus avec imagemin pour du svg.
D'après je ne suis pas choqué de faire ça de manière séparée afin de 
traiter le bitmap d'un coté et de l'autre le vectoriel.

:)

**Comment by raphaelgoetter** [comment]
> Peut être la réduction d'image pour le svg n'est pas fortement probant
comme c'est du vectoriel.

Stéphanie ne serait pas de cet avis ;)
http://www.alsacreations.com/tuto/lire/1602-reduire-le-poids-image-svg-illustrator.html

> Ou bien qu'il y a peut être des bugs connus avec imagemin pour du svg.

Actuellement, dans Alstart imagemin traite déjà tous les fichiers (SVG compris). C'est juste qu'ils sont séparés, ce qui complique la tâche.

Merci pour ton retour.

**Comment by blupdew** [comment]
L'optimisation des SVG est très probante puisqu'on peut gagner 20 à 80% de poids avec imagemin. Si le script les sépare, c'est que les options de compression sont différentes (lignes 59 et 65), mais on peut certainement les fusionner si on y tient. Cependant rares sont les projets où on met toutes les images en vrac dans le même dossier n'est-ce pas ?

**Comment by raphaelgoetter** [comment]
J'ai surtout peur que plus on a de variables (je parle des 4 ou 5 chemins pour les images), plus on risque de se planter ou d'oublier de les remplir.

**Comment by hiwelo** [comment]
Perso, j'avoue que je suis plutôt partant pour un dossier img & svg commun :)

**Comment by hiwelo** [comment]
imagemin() est assez intelligent pour effectuer les optimisations selon le format dans le même dossier

**Comment by raphaelgoetter** [comment]
Tant que j'y suis, je viens de tester la version imagemin de alstart.

Elle fonctionne mais un truc me paraît bizarre : il y a une virgule (de trop ?) à la fin de `{cleanupIDs:false}],` 

Bizarre, non ?

**Comment by hiwelo** [comment]
Dans un tableau ou un objet Javascript ça ne pose pas de soucis :) 
Mais oui, s'il n'y a pas d'autres entrées on peut la retirer, non @blupdew ?

**Comment by blupdew** [comment]
Affirmatif.

**Comment by raphaelgoetter** [comment]
OK...
Du coup, vous voulez que je le fasse ? (histoire de se bouger un peu quoi)

**Comment by hiwelo** [comment]
Si tu le fais, ça évitera une *pull request* vu que tu es *owner* ;)

**Comment by raphaelgoetter** [comment]
J'en profite pour dire que c'est chiant d'avoir des noms de variables avec des underscores ( ?)

**Comment by raphaelgoetter** [comment]
Done.
