### ISSUE TITLE
Proposition de workflow bi : production et "intermédiaire"

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/alstart#2]
Objectif : 

- Certains de nos clients ont besoin d'une version livrée modifiable (non minifiée ni concaténée)
- Dans d'autres cas, on met en prod et on ne touche plus aux fichiers

Test (qui fonctionne) : https://gist.github.com/raphaelgoetter/39e8923d282b4007ac98

Fonctionnement :

- Dossier de départ : `/src`
- Dossier final : `/dist`
- Si tâche `gulp build` alors les fichiers de `/dist` ne sont ni minifiés ni concaténés, ni uncss ni critical
- Si tâche `gulp prod` alors c’est la totale, madame !

Avis ? Commentaires ? Moyen de faire plus propre, plus intelligent ?

**Comment by hiwelo** [comment]
Je teste ce workflow actuellement sur la nouvelle version de mon site perso que j'intègre en ce moment (_pour enfin finir un jour mon site_) et je trouve que c'est plutôt pas mal.
Ce que j'ai utilisé c'est un mix des deux : les variables et les tâches basiques d'Alstart et le *gist* que tu proposes.

**Comment by raphaelgoetter** [comment]
Up

**Comment by raphaelgoetter** [comment]
A priori résolu dans quelques heures (ou pas)
