### ISSUE TITLE
Browsersync "çamarchepas.org"

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/alstart#4]
Y'a-t-il un truc particulier à faire pour que Browsersync fonctionne ?

J'essaye ça : 

```
// Tâche "watch" = je surveille LESS et HTML
gulp.task('watch', function () {
  browserSync({
    proxy: 'http://localhost:5000'
  });
  gulp.watch(source + '/assets/css/*.less', ['build', browserSync.reload]);
  gulp.watch(source + HTMLfiles, ['build']);
});
```

Ça ouvre automatiquement un onglet Chrome avec l'url `http://localhost:3000/` puis ça charge dans le vide et finalement, systématiquement : 

> Aucune donnée reçue. ERR_EMPTY_RESPONSE

J'ai raté quoi ?

**Comment by id2** [comment]
Je pense que ça pourrait venir de ceci : 
proxy: 'http://localhost:5000'
un onglet Chrome avec l'url http://localhost:3000/

pas le même port donc pas de réponse.

**Comment by raphaelgoetter** [comment]
Euh on est d'accord que j'ai aussi bien entendu essayé avec 5000 dans l'url et aussi en mettant 3000 dans le gulpfile.

Cela ne fonctionne pas dans aucun des cas que j'ai testé.

Cette issue **n'est pas** résolue chez moi

**Comment by blupdew** [comment]
Résolu, il était configuré en proxy, ce qui marche quand il y a déjà un serveur local qui tourne par exemple LAMP. Il est désormais en server (= standalone). J'ai laissé l'option au cas où pour plus tard.
