### ISSUE TITLE
Mettre à jour KNACSS

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/alstart#6]
KNACSS n'est pas à jour sur Alstart, ce serait bien de de faire de temps en temps.

(je m'auto-assigne)

**Comment by id2** [comment]
pas obligé si on sort les vendors via un gitignore il sera mis à jour 
automatiquement via bower

**Comment by raphaelgoetter** [comment]
Ah oui, en effet on dirait que KNACSS n'est plus inclus en dure dans Alstart. Résolu.
